add error message

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,10 +15,10 @@ on:
 jobs:
   build:
 
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
       
     - name: Install apt-get packages
       run: |
@@ -33,21 +33,15 @@ jobs:
         
     - name: Install WasmEdge
       run: |
-        VERSION=0.12.1
+        VERSION=0.13.5
         curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- -e all --version=$VERSION -p /usr/local
     
-    - name: sales_tax_rate
+    - name: cargo build and wasmedge
       run: |
-        cd sales_tax_rate
         cargo build --target wasm32-wasi --release
         wasmedgec target/wasm32-wasi/release/sales_tax_rate_lookup.wasm sales_tax_rate_lookup.wasm
         nohup wasmedge sales_tax_rate_lookup.wasm &
         echo $! > sales_tax_rate.pid
-
-    - name: order_total
-      run: |
-        cd order_total
-        cargo build --target wasm32-wasi --release
         wasmedgec target/wasm32-wasi/release/order_total.wasm order_total.wasm
         nohup wasmedge --env "SALES_TAX_RATE_SERVICE=http://127.0.0.1:8001/find_rate" order_total.wasm &
         echo $! > order_total.pid
@@ -63,7 +57,15 @@ jobs:
           echo -e "Execution Fail!"
           exit 1
         fi
-        kill -9 `cat sales_tax_rate/sales_tax_rate.pid`
-        rm sales_tax_rate/sales_tax_rate.pid
-        kill -9 `cat order_total/order_total.pid`
-        rm order_total/order_total.pid
+        resp=$(curl http://localhost:8002/compute -X POST -d @error_order.json)
+        echo "$resp"
+        if [[ $resp == *"error"* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        kill -9 `cat sales_tax_rate.pid`
+        rm sales_tax_rate.pid
+        kill -9 `cat order_total.pid`
+        rm order_total.pid
